resolver: lts-8.2

packages:
- '.'
- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 838b064d8a59286142aa2fe14434fe7601896ddb
  extra-dep: true

flags: {}
extra-package-dbs: []
nix:
  packages: [gmp]
