resolver: lts-8.2

packages:
- '.'
- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 838b064d8a59286142aa2fe14434fe7601896ddb
  extra-dep: true

extra-deps:
- cryptonite-0.24
- cryptonite-openssl-0.6
- foundation-0.0.13
- memory-0.14.6

flags: {}
extra-package-dbs: []
nix:
  packages: [gmp, openssl]
